<style>
[data-testid="stSidebar"] {background-color: #f7f9fc; display: flex; flex-direction: column;}
.big-font {font-size:28px !important; font-weight:bold; color:#0B3D91; margin-bottom:15px;}
.stMetricValue {color: #1E81B0; font-weight:bold;}
.stMetricLabel {color: #0B3D91; font-weight:bold;}
.card {background-color:#ffffff; padding:15px; border-radius:12px; box-shadow: 0 4px 8px rgba(0,0,0,0.15); margin-bottom:15px;}
.card-title {font-size:16px; font-weight:bold; color:#0B3D91;}
.card-text {font-size:14px; color:#333;}
div.stButton > button:first-child {
    background-color: #003366;
    color: white;
    border-radius: 4px;
    padding: 8px 20px;
    border: none;
    font-size: 15px;
}
div.stButton > button:first-child:hover {
    background-color: #0055a5;
}
.eval-title {
    font-size: 32px;
    font-weight: bold;
    text-align: center;
    margin-bottom: 30px;
    color: #0b3d91;
}
.stLinkButton > a {
    display: inline-block;
    padding: 14px 28px;
    border-radius: 8px;
    font-weight: 600;
    text-align: center;
    transition: all 0.3s ease;
    background-color: #0b3d91;
    color: white;
    border: none;
}
.stLinkButton > a:hover {
    background-color: #072c66;
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(0,0,0,0.2);
}
</style>